### ISSUE TITLE
Add data model

### ISSUE THREAD

**Issue by thuselem** [thuselem/teergrube#9]
Discuss a good data model that will handle email threads. Only one sender and recipient should be needed. Add the models to `models.py`

**Comment by thuselem** [comment]
I added `models.py` with `Message` and `User` classes. These classes are likely incomplete. I will go through some raw emails to see what else we might be missing. 

One thing to consider. Should a `User` be allowed multiple email addresses? As it stands now, they are allowed only one.

**Comment by jarfgit** [comment]
Data models complete for current version.
